### ISSUE TITLE
citypicker

### ISSUE THREAD

**Issue by YERUVAKONIREDDY** [evgenyneu/Cosmos#101]
Please consider submitting the following information (if relevant):

* Library setup method: file, Carthage, CocoaPods or Swift Package Manager.
* Version of the library. Example: 8.0.//dont know
* Xcode version. Example: 9.1.
[CityPicker-master.zip](https://github.com/evgenyneu/Cosmos/files/1851256/CityPicker-master.zip)

* OS version. Example: iOS 11.2.0.

**Comment by evgenyneu** [comment]
Hi @YERUVAKONIREDDY, do you have any issue with the library? It is not clear from the text that you wrote.

**Comment by YERUVAKONIREDDY** [comment]
Yes it's not working. For me

**Comment by evgenyneu** [comment]
I'm sorry it's not working. Can you please describe the problem in detail: how you use the library, what went wrong? If relevant, show some error messages and/or attach screenshots, so I can help you? I see you attached a file. However, I don't provide general programming help and can't look into it. Please describe your problem in words. :)

**Comment by evgenyneu** [comment]
Closing this issue for a lack of clarification on the issue. Feel free to reopen when needed.
