### ISSUE TITLE
"Failed to set user defined inspected property on UIView"

### ISSUE THREAD

**Issue by ccynn** [evgenyneu/Cosmos#104]
* Library setup method: CocoaPods
* Version of the library. 15
* Xcode version. 9.2
* OS version. Example: iOS 11.2

Hi,

I am receiving the below error (only for the totalStars attribute) when running the application and am not necessarily sure how to resolve. I tried manually inputting 5 in the attributes inspector, programmatically setting it to 5, leaving it to its default value, and deleting/re-adding the uiview.

Any guidance is appreciated!

**Error Message:
Failed to set (totalStars) user defined inspected property on (UIView): [<UIView 0x10c11a750> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key totalStars.**

**Comment by evgenyneu** [comment]
Hi @ccynn, thanks for reporting. An issue than may be similar was reported in #23. Let me know if the solution helps.

**Comment by ccynn** [comment]
@evgenyneu thanks for the quick reply! so i figured it out...

i had the stars uiview embedded in parent uiview and for some reason the parent uiview had a runtime user-defined attribute of totalStars, which was why the error was throwing. just didn't realize it since they were both uiviews.

in any case, i still deleted the runtime attributes in the stars uiview and have them programmatically setup.

thanks for the guidance!

**Comment by evgenyneu** [comment]
I'm glad the problem is solved! :)
