### ISSUE TITLE
Stars values not updating on touch

### ISSUE THREAD

**Issue by IOSDevelopereHere** [evgenyneu/Cosmos#109]
Please consider submitting the following information (if relevant):

* Library setup method:  CocoaPods
* Version of the library. Example: 15.0
* Xcode version. Example: 9.3
* OS version. Example: iOS 10.3

    @IBOutlet weak var stars_honesty: CosmosView!

stars_honesty.didFinishTouchingCosmos = sethonesty //// written in viewdidload

func sethonesty(_ rating: Double) {
        honesty = rating
        stars_honesty.rating = rating
    }

done all but still  sethonesty func dont runs...
Need help

**Comment by evgenyneu** [comment]
Hi @IOSDevelopereHere, have a look at how the touch events are reported in the demo app [here](https://github.com/evgenyneu/Cosmos/blob/master/Demo/ViewController.swift), you can try mimicking this in your app as well. Let me know if it works for you.

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
