### ISSUE TITLE
Issue Cosmos in TableViewCells

### ISSUE THREAD

**Issue by abraham28s** [evgenyneu/Cosmos#112]
Please consider submitting the following information (if relevant):

* Library setup method:  CocoaPods.
* Version of the library. current
* Xcode version. Example: current
* OS version. Example: current.

I have a problem where I have a cosmos view inside some tableviewcells, the problem is when I set rating the didSelectRow methos gets called and because of my app, another view controller is presented, I tried removing the listen of touch within the cell of the specific cosmos view but then the user interaction become disabled.

Sorry for bad english.

Do you have any idea of how can I solve this?

Thank you.

**Comment by evgenyneu** [comment]
Hi @abraham28s, thanks for reporting. Could you show a screenshot please?

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.

**Comment by yuravake** [comment]
@evgenyneu  Hi, I have the same issue here. As far as I understand CosmosView passes touch events to the table view cell, which triggers didSelectRow. I'm wondering how we can avoid this. Maybe add a property to disable passing of touchesBegan to superview?

**Comment by evgenyneu** [comment]
@yuravake fell free to submit a pull request, if this solution fixes your problem. We can add a property to settings that prevents calling `super.touchesBegan`.

**Comment by yuravake** [comment]
@evgenyneu  please review https://github.com/evgenyneu/Cosmos/pull/131

**Comment by evgenyneu** [comment]
Thanks for the update @yuravake. I've released it in version 18. Did it solve your issue with the table view?

**Comment by yuravake** [comment]
@evgenyneu yeah, it did. Everything is correct now. Thanks!

**Comment by Manoojkumar** [comment]
so what is the solution, I am getting the same issue

**Comment by evgenyneu** [comment]
@Manoojkumar, try setting:

```
cosmosView.settings.passTouchesToSuperview = false
```

Let me know if it works. :)

**Comment by Manoojkumar** [comment]
@evgenyneu, Thanks it worked.
