### ISSUE TITLE
storyboard: error: IB Designables: Failed to render and update auto layout status for ViewController (KPX-Ig-6W8): dlopen(Cosmos.framework, 1): no suitable image found.

### ISSUE THREAD

**Issue by gurjitdhiman** [evgenyneu/Cosmos#113]
xcode unable to render view for Cosmos in storyboard and xib. hence I am not able to work on other constrains. :-(

**Comment by anirudhamahale** [comment]
Yup the above solution does work!👍🏻

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
