### ISSUE TITLE
how to customize font

### ISSUE THREAD

**Issue by mohamedmontser** [evgenyneu/Cosmos#115]
Please consider submitting the following information (if relevant):

* Library setup method: file, Carthage, CocoaPods or Swift Package Manager.
* Version of the library. Example: 8.0.
* Xcode version. Example: 9.4.1.
* OS version. Example: iOS 10.3.2.

**Comment by evgenyneu** [comment]
@mohamedmontser, the customisation options for the text are described [here](https://github.com/evgenyneu/Cosmos/wiki/Cosmos-configuration#text-settings). Let me know if it helps. :)

**Comment by evgenyneu** [comment]
Closing the issue, feel free to reopen if needed.
