### ISSUE TITLE
Jagged vector images in custom star image.

### ISSUE THREAD

**Issue by Madmar1k** [evgenyneu/Cosmos#116]
Hi!
I'm setting custom image from PDF files.
Settings of files set to Preserve Vector Data and Scales: Single Scale.
` cosmosView.settings.filledImage = UIImage(named: "rate_icon_A")
       cosmosView.settings.emptyImage = UIImage(named: "rate_icon_B")`
`cosmosView.settings.starSize = 50`
But image looks jagged.
Tried to disable `improvePerformance()` and init with custom frame.
When I place that images to UIImageView it's looks fine.
How can I solve it?
* Library setup method: CocoaPods.
* Version of the library. ~> 15.0.
* Xcode version: 9.4.1.
* OS version: iOS 11.4.

**Comment by evgenyneu** [comment]
Thanks for reporting @Madmar1k. Do you mind attaching the image file so I can try it?

**Comment by Madmar1k** [comment]
[rating_stars.zip](https://github.com/evgenyneu/Cosmos/files/2154461/rating_stars.zip)
OK.

**Comment by evgenyneu** [comment]
Thanks for the image. I could reproduce the issue. A quick fix would be to resize the PDF to 50 pixels, see the attached demo app. I'm not sure why it was blurry with the original smaller images. I found a discussion of the issue that could be similar to yours [here](https://stackoverflow.com/questions/33612820/xcode-vector-images-from-pdf-bad-quality). Let me know if it helps.

[CosmosWithImage.zip](https://github.com/evgenyneu/Cosmos/files/2157309/CosmosWithImage.zip)

**Comment by Madmar1k** [comment]
Thanks, it helps. Manually resized PDF images.
