### ISSUE TITLE
Can not set 0.5 for rating values

### ISSUE THREAD

**Issue by c1800054work** [evgenyneu/Cosmos#117]
Please consider submitting the following information (if relevant):

* Library setup method: CocoaPods
* Version of the library. Example: 16.0.
* Xcode version. Example: 9.4.1.
* OS version. Example: iOS 11.

i set Fil Mode to 1, and i can set 1, 1.5, 2, 2.5, 3, 3.5....
But i can not set 0.5 for rating values

**Comment by evgenyneu** [comment]
Hi, this might help:

```Swift
cosmosView.settings.minTouchRating = 0
```

Please see the [settings manual](https://github.com/evgenyneu/Cosmos/wiki/Cosmos-configuration) for more details.

**Comment by c1800054work** [comment]
wow!!!
it works!!! thanks for solution.
