### ISSUE TITLE
emptyImage does not get my custom image

### ISSUE THREAD

**Issue by UzumakiAlfredo** [evgenyneu/Cosmos#118]
Hi.
I tried both storyboard and the code, but I can't set my custom empty image to my cosmos view.
here is my code: 
`fourStarRateBar.settings.emptyImage = #imageLiteral(resourceName: "emptyStar")
`what should I do!?
mabe the image size shuld be something special?

**Comment by evgenyneu** [comment]
Hi @UzumakiAlfredo, thanks for reporting the issue. Could you isolate the problem into a simple app and attach here, so I can have a look please?

**Comment by UzumakiAlfredo** [comment]
It worked on new project that I wanted to send for you!
I don't know whats wrong with my main project :(

**Comment by UzumakiAlfredo** [comment]
I Found the issue! when I copy & paste a Cosmos view in storyboard, to duplicated my Cosmos view, & if I don't assign any image for border before copy, the problem, occurred.
