### ISSUE TITLE
 do'nt can rest rating to empty star after rate it by touching view 

### ISSUE THREAD

**Issue by omarhassansadek** [evgenyneu/Cosmos#121]
Please consider submitting the following information (if relevant):

* Library setup method: file, Carthage, CocoaPods or Swift Package Manager.
* Version of the library. Example: 8.0.
* Xcode version. Example: 8.3.3.
* OS version. Example: iOS 10.3.2.

**Comment by rqbctg** [comment]
same problem here

**Comment by evgenyneu** [comment]
Thanks for reporting, have you tried the solution in #73?
