### ISSUE TITLE
Cosmos needs to be updated for Swift 4.2 compatibility.

### ISSUE THREAD

**Issue by ethanwa** [evgenyneu/Cosmos#122]
Cosmos needs to be updated for Swift 4.2 compatibility. I'm getting a request to convert to it in Xcode 10 GM.

**Comment by destrovel** [comment]
Cosmos is compliant with swift 4.2 using the built-in conversion in Xcode. It doesn't even change anything. Theres a single warning about a deprecated method text.characters[] but it still works even.

**Comment by evgenyneu** [comment]
Cosmos was updated to Swift 4.2 in version `17`. Please let me know if you are still having issues.

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
