### ISSUE TITLE
VIDEO TUTORIAL on YouTube

### ISSUE THREAD

**Issue by rebeloper** [evgenyneu/Cosmos#125]
Hi,

I really like your repository. Used it in several of my apps and thought I make a video tutorial on how to use it!

You can take a look at it here: https://www.youtube.com/watch?v=Y4A_y29cy7Q&t=15s

If you like it consider adding it to your README with the following image: https://i.ytimg.com/vi/Y4A_y29cy7Q/maxresdefault.jpg

Alex.

**Comment by evgenyneu** [comment]
Done! This is some high-quality material. Thank you very much! 👍

**Comment by rebeloper** [comment]
You are welcome! I'm also a fan of Dodo, Auk, Moa and KeychainSwift too. Most probably will do tutorials on those too in the near future.

**Comment by evgenyneu** [comment]
That will be very useful for the Swift community. Keep it up! 👍
