### ISSUE TITLE
Compile error in struct CosmosAccessibility and in struct StarLayer

### ISSUE THREAD

**Issue by AdnanAfsari** [evgenyneu/Cosmos#127]
I Just added the CosmosDistrib.swift file in my project and i am getting the following errors.

inside the "struct CosmosAccessibilit" from the method "update" i am getting  this error

'Type 'UIAccessibilityTraits' (aka 'UInt64') has no member 'adjustable'

and inside the "struct StarLayer" from the method "create"  i am getting error
'Type 'CALayerContentsGravity' (aka 'NSString') has no member 'resize' 

* Library setup method: file
* Version of the library. Example: 8+.
* Xcode version. Example: 10.1.
* OS version. Example: iOS 12.1.

**Comment by evgenyneu** [comment]
Thanks for reporting the issue, @AdnanAfsari. I've just created a new demo app in Xcode 10.1 and it compiled fine for me. Does the attached project work for you?

[DemoCosmos.zip](https://github.com/evgenyneu/Cosmos/files/2592667/DemoCosmos.zip)

**Comment by evgenyneu** [comment]
I'm glad it worked! 👍
