### ISSUE TITLE
 The Cosmos binary use incompatible versions of Swift 5

### ISSUE THREAD

**Issue by UzumakiAlfredo** [evgenyneu/Cosmos#137]
The Cosmos binary use incompatible versions of Swift 5

Please update it.

**Comment by evgenyneu** [comment]
Thanks for reporting the issue, @UzumakiAlfredo. I've created a new app in Xcode 10.2 (10E125) and Cosmos worked fine (please see the demo project attached). What kid of issues do you have?

[DemoCosmos.zip](https://github.com/evgenyneu/Cosmos/files/3037608/DemoCosmos.zip)

**Comment by UzumakiAlfredo** [comment]
You are right. I tested in on a new project & it works.
Seems like that is my project issue...
Sorry.
