### ISSUE TITLE
Update to swift 5

### ISSUE THREAD

**Issue by jamalalayq** [evgenyneu/Cosmos#138]
Please update .swift-version to 5

**Comment by evgenyneu** [comment]
Thanks for reporting, @jamalalayq. What kind of issues are you having? We've checked (#137) the current version of Cosmos in Xcode 10.2, it worked fine.

**Comment by jamalalayq** [comment]
Dear, 
after update Cosmos to to lastest version, still Xcode give warning to update Cosmos to version 5
after check Cosmos source code on Githup i found (.swift-version) file still Swift version is 4.2, i think issue in this file.

**Comment by evgenyneu** [comment]
You are right @jamalalayq, I've missed this problem. This now has been fixed in version 19. It needs to be used with CocoaPods 1.7.0 (install beta with `gem install cocoapods --pre` if you don't have it yet). Thanks!
