### ISSUE TITLE
Plans to support Swift Package Manager

### ISSUE THREAD

**Issue by kylebrowning** [evgenyneu/Cosmos#143]
With XCode 11 GM around the corner. are there any plans to support SPM with a `Package.swift`

**Comment by evgenyneu** [comment]
@kylebrowning thanks for the nudge. :) Yes, absolutely. Feel free to submit a pull request.

**Comment by ethanwa** [comment]
I second this! Thank you!

**Comment by evgenyneu** [comment]
Thanks to @gcharita for [adding Swift Package Manager support](https://github.com/evgenyneu/Cosmos/pull/145). Please report here if you find any issues. We will also probably need to add installation instructions for Swift Package manager to Readme.

**Comment by gunnarsson** [comment]
The support is there and there are instructions in the readme, I suggest closing this issue 👍

**Comment by kylebrowning** [comment]
> The support is there and there are instructions in the readme, I suggest closing this issue 👍 

Yeah that wasn't the case when I opened this ticket.
