### ISSUE TITLE
Is Cosmos using UIWebView?

### ISSUE THREAD

**Issue by JKMATK** [evgenyneu/Cosmos#144]
I was pushing an app to testflight and I received an email from apple that I'm using UIWebView and that UIWebView is depreciated. The app was accepted for testflight but seems like it can be an issue in the near future.
Thank you so much in advance

**Comment by evgenyneu** [comment]
Hi, no, Cosmos is not using a web view.

**Comment by JKMATK** [comment]
Thank you so much!
