### ISSUE TITLE
can we set text on left side?

### ISSUE THREAD

**Issue by forTJ555** [evgenyneu/Cosmos#147]
Please consider submitting the following information (if relevant):

* Library setup method: file, Carthage, CocoaPods or Swift Package Manager.
* Version of the library. Example: 8.0.
* Xcode version. Example: 8.3.3.
* OS version. Example: iOS 10.3.2.

**Comment by evgenyneu** [comment]
Thanks for the question @forTJ555. No, the library can't do that at the moment. But the text can easily be added as a UILabel and pinned to the left of the Cosmos view with auto layout.

**Comment by forTJ555** [comment]
thanks for updating
