### ISSUE TITLE
how use in SwiftUI ?

### ISSUE THREAD

**Issue by c941010623** [evgenyneu/Cosmos#152]
Please consider submitting the following information (if relevant):

* Library setup method: file, Carthage, CocoaPods or Swift Package Manager.
* Version of the library. Example: 8.0.
* Xcode version. Example: 8.3.3.
* OS version. Example: iOS 10.3.2.

**Comment by evgenyneu** [comment]
https://github.com/evgenyneu/Cosmos/wiki/Using-Cosmos-with-SwiftUI
