### ISSUE TITLE
App doesn't start with iOS 13.3.1

### ISSUE THREAD

**Issue by JE4GLE** [evgenyneu/Cosmos#157]
* Library setup method: CocoaPods
* Version of the library: 19.0.3
* Xcode version: 11.3.1
* OS version: iOS 13.3.1

When trying to start the app on iOS 13.3.1 the following error occurs. It works fine on iOS 13.3.

	dyld: Library not loaded: @rpath/Cosmos.framework/Cosmos
	  Referenced from: /private/var/containers/Bundle/Application/1FF3E21A-D0FA-413C-9046-4576BC24E3F0/MyApp.app/MyApp
	  Reason: no suitable image found.  Did find:
		/private/var/containers/Bundle/Application/1FF3E21A-D0FA-413C-9046-4576BC24E3F0/MyApp.app/Frameworks/Cosmos.framework/Cosmos: code signature invalid for '/private/var/containers/Bundle/Application/1FF3E21A-D0FA-413C-9046-4576BC24E3F0/MyApp.app/Frameworks/Cosmos.framework/Cosmos'

	/private/var/containers/Bundle/Application/1FF3E21A-D0FA-413C-9046-4576BC24E3F0/MyApp.app/Frameworks/Cosmos.framework/Cosmos: stat() failed with errno=25
	/private/var/containers/Bundle/Application/1FF3E21A-D0FA-413C-9046-4576BC24E3F0/MyApp.app/Frameworks/Cosmos.framework/Cosmos: code signature invalid for '/private/var/containers/Bundle/Application/1FF3E21A-D0FA-413C-9046-4576BC24E3F0/MyApp.app/Frameworks/Cosmos.framework/Cosmos'

	/private/var/containers/Bundle/Application/1FF3E21A-D0FA-413C-9046-4576BC24E3F0/MyApp.app/Frameworks/Cosmos.framework/Cosmos: stat() failed with errno=1
	/private/var/containers/Bundle/Application/1FF3E21A-D0FA-413C-9046-4576BC24E3F0/MyApp.app/Frameworks/Cosmos.framework/Cosmos: code signature invalid for '/private/var/containers/Bundle/Application/1FF3E21A-D0FA-413C-9046-4576BC24E3F0/MyApp.app/Frameworks/Cosmos.framework/Cosmos'

	/private/var/containers/Bundle/Application/1FF3E21A-D0FA-413C-9046-4576BC24E3F0/MyApp.app/Frameworks/Cosmos.framework/Cosmos: stat() failed with errno=1

_Edit 1: I wrote, that it didn't build. This is wrong. It does build, but not start.
Edit 2: Formatting_

**Comment by JE4GLE** [comment]
Seams to be a side spread issue:

- https://github.com/ionic-team/capacitor/issues/2383
- https://github.com/Alamofire/Alamofire/issues/3051
- https://github.com/flutter/flutter/issues/49693

**Comment by grandsilence** [comment]
the same issue on iPhone XR iOS 13.3.1

**Comment by dkk** [comment]
Same issue on iPhone 11 Pro 13.3.1, on simulator it works.

**Comment by grandsilence** [comment]
# Full report about issue

## Target device
Device: **iPhone XR on iOS 13.3.1**  

## Dev machine
Mac OS: Catalina `10.15.4`
XCode: `11.4.1`
CocoaPods version: `1.9.1`

### Dev machine: flutter
Flutter version: `1.17.1 • channel stable`
Flutter framework: `revision f7a6a7906b • 2020-05-12 18:39:00 -0700`
Engine: `revision 6bc433c6b6`
Tools: `Dart 2.8.2`

### Dev machine: xCode exception
```
dyld: Library not loaded: @rpath/Flutter.framework/Flutter
  Referenced from: /private/var/containers/Bundle/Application/5C2B4581-F945-4E44-BD28-55C462054CAC/Runner.app/Runner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/5C2B4581-F945-4E44-BD28-55C462054CAC/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for '/private/var/containers/Bundle/Application/5C2B4581-F945-4E44-BD28-55C462054CAC/Runner.app/Frameworks/Flutter.framework/Flutter'

(lldb)
```
