### ISSUE TITLE
Fix rating update responsiveness in Demo (main controller)

### ISSUE THREAD

**Issue by MaxZheleznyy** [evgenyneu/Cosmos#160]
**Old behavior** - https://d.pr/v/tItCsG

**Suggested behavior** - update all ratings at the same time

**Reasons:**

- Current version requires a user to remember which rating is currently working with the score scale
- I (as a user) may want to see how other ratings will change based on a change with a specific rating

**(possible) Interesting information:**

- Version of the library - 21.0.0
- Xcode version - 11.3.1 (11C504)
- OS version - Any

**Comment by evgenyneu** [comment]
@MaxZheleznyy, thanks, sorry I don't understand what you want to accomplish in the demo app. Can you explain a bit more please?

**Comment by MaxZheleznyy** [comment]
@evgenyneu absolutely

From my point of view, the current system is a _little_ bit misleading. 
I (as a user) expect that every rating (Full, Half and Precise) will be updated no matter which one has changed. 
Without such functionality, a user ended up wondering (especially if he/she got distracted for a moment) - why is the rating slider showing me 4 (for example), but "Full" rating is only 2 (again as an example). The first thought, for such behavior, is "have I broken something?".

Hope that will give you an idea ;)

**Comment by MaxZheleznyy** [comment]
@evgenyneu hi 👋 
Will be pleased to hear your thoughts/suggestions/questions about my previous comment

**Comment by evgenyneu** [comment]
@MaxZheleznyy thanks for the reminder. That's awesome, thanks for improving the demo app.

**Comment by MaxZheleznyy** [comment]
awesome 👏 
Thank you for such a great app 👍
