### ISSUE TITLE
First touch in collectionView

### ISSUE THREAD

**Issue by oguzveozturk** [evgenyneu/Cosmos#170]
* Library setup method:CocoaPods 
* Version of the library. last version
* Xcode version.: 11.7
* OS version.: iOS 13

<img src="https://media.giphy.com/media/fu1lwM0RfTvXtWO2fN/giphy.gif" width="150" height="230" />

Hi,
When cosmos inside collectionViewCell scrolling is not working properly. because when i start scrolling at the collectionview's random point, it is working. But when my first touch position is on the cosmosView, scroll is not working. After that my touches triggered cosmosView unless rating is finished. 
I want to cosmosView only trigger by horizontal touches or single taps. Any suggestions?

👏🏼 ln the meantime, thank you so much for your attention and participation👏🏼

**Comment by evgenyneu** [comment]
Hi @oguzveozturk, good question. Did you try enabling "Can cancel on scroll" in the Attributes Inspector for the **scroll view**?

**Comment by oguzveozturk** [comment]
Yes, i did. Same result unfortunately.

**Comment by evgenyneu** [comment]
Ok,  is it possible to isolate the issue in a demo app and attach a sample project here so I can have a look?

**Comment by oguzveozturk** [comment]
Pk

Okey. I do my best. Thanks

**Comment by oguzveozturk** [comment]
hi @evgenyneu you can look this:
[Demoapp.zip](https://github.com/evgenyneu/Cosmos/files/5192931/Demoapp.zip)

**Comment by evgenyneu** [comment]
It works well for me when I comment out this line in `ViewController.swift`

```Swift
// cosmosView.settings.disablePanGestures = true
```

**Comment by oguzveozturk** [comment]
Sorry @evgenyneu but not working usually. yes, sometimes scroll event triggered first. but sometimes : (

<img src="https://media.giphy.com/media/gFoOVIInDrCgoITpas/giphy.gif" width="270" height="213" />

**Comment by evgenyneu** [comment]
> sometimes scroll event triggered first. but sometimes : (

Hmm, yeah, this is messy. I think the problem is that the Scroll View tries to distinguish between scrolling and tapping the Cosmos view. If the interval between tap and scroll is small, it does the scroll (when [Delay Touch Down](https://developer.apple.com/documentation/uikit/uiscrollview/1619398-delayscontenttouches) is on). Otherwise - the tap. I don't know how to solve this problem even in principle, it's fuzzy.

**Comment by oguzveozturk** [comment]
Okey i understand. But I must say; on the simulator, mouse clicking much pointy than finger touches. I ran it on the real device. Still not perfect but so much better than before. 

 Thank you for response again🙏🏼

**Comment by evgenyneu** [comment]
> on the simulator, mouse clicking much pointy than finger touches. I ran it on the real device. 

Oh, that's good!
