### ISSUE TITLE
Xcode 12 'IPHONEOS_DEPLOYMENT_TARGET' warning

### ISSUE THREAD

**Issue by gilrodar** [evgenyneu/Cosmos#171]
Please consider submitting the following information (if relevant):

`The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.`

* CocoaPods
* Version of the library. 
21.0.0
* Xcode version. 
12.0
* OS version.
 iOS 14

**Comment by evgenyneu** [comment]
Hi @gilrodar, thanks for reporting the issue. Is it possible to isolate the issue in a small demo app and attach here so I can have a look?

**Comment by gilrodar** [comment]
I only added Cosmos with SwiftPackage and built the application with cmd + b. After that it shows this warning. But only with Xcode 12

**Comment by evgenyneu** [comment]
That's good to know, I'll check that once Xcode 12 gets out of Beta.

**Comment by gilrodar** [comment]
I think Xcode 12 is no longer a beta. 
You can download the version from the App Store.

<img width="935" alt="Captura de Pantalla 2020-09-17 a la(s) 20 42 59" src="https://user-images.githubusercontent.com/13817108/93545586-66fab000-f926-11ea-8321-b0207cbdcc3f.png">

**Comment by evgenyneu** [comment]
> I think Xcode 12 is no longer a beta.
> You can download the version from the App Store.

Oh, I did not know that, thanks. I'll have a look.

**Comment by evgenyneu** [comment]
Fixed in version `23.0`. Let me know if it works for you.

**Comment by gilrodar** [comment]
Thanks, with Swift Package not update to version 23.0. :(

**Comment by evgenyneu** [comment]
Oh, is there an error?

**Comment by gilrodar** [comment]
There is no error, only the version 23 is not downloaded. I give in update and the version 21 is kept.

I already deleted and re-downloaded and it still brings version 21.0.0

**Comment by evgenyneu** [comment]
Computers suck! It worked for me though:

https://drive.google.com/file/d/112yn6rgGQRvIzbg-3vE_ucAV6m8a4Qk_/view?usp=sharing

**Comment by 4brunu** [comment]
It's working for me.

**Comment by gilrodar** [comment]
Ready it works, I had to delete the swift package and download it again and it brought me the 23.00 version
