### ISSUE TITLE
How to disable tapping?

### ISSUE THREAD

**Issue by lsamaria** [evgenyneu/Cosmos#179]
Please consider submitting the following information (if relevant):

* Library setup method: file, Carthage, CocoaPods or Swift Package Manager.
-cocoapods

* Version of the library. Example: 8.0.
-cosmos (22.1.0) (in podfile.lock)

* Xcode version. Example: 8.3.3.
-xcode 12.2

* OS version. Example: iOS 10.3.2.
-iOS 13 and  up

How can I disable tapping so that `.didTouchCosmos` and `.didFinishTouchingCosmos` are only triggered via a drag?

**Comment by evgenyneu** [comment]
@lsamaria this is not possible, unfortunately.

**Comment by lsamaria** [comment]
thanks!
