### ISSUE TITLE
How to set empty image for empty start(non partially filled as well)

### ISSUE THREAD

**Issue by Karthikmoback** [evgenyneu/Cosmos#180]
I was able to set the start with decimal precise to show the star with partially filled of stars, But empty image is set to partially filled star , which i dont want to happen.
Need to show like this
<img width="131" alt="Screenshot 2021-01-18 at 2 59 53 PM" src="https://user-images.githubusercontent.com/59563436/104897239-2a0afc80-599e-11eb-948e-12d84f929295.png">

Instead of this
![IMG_6C0E5D923EC4-1](https://user-images.githubusercontent.com/59563436/104897267-30997400-599e-11eb-9393-cd0cef7b5bcf.jpeg)

**Comment by evgenyneu** [comment]
Hi @Karthikmoback, do you use custom star images?

**Comment by Karthikmoback** [comment]
yes, here is my settings in storyboard.
<img width="262" alt="Screenshot 2021-01-18 at 4 04 15 PM" src="https://user-images.githubusercontent.com/59563436/104904243-f8e2fa00-59a6-11eb-9f08-da1bf3d98d0c.png">

**Comment by evgenyneu** [comment]
Oh, so your "empty" image has the black border. Did you try without setting the "empty" image? Or maybe use an emty image which is blank/transparent?

**Comment by Karthikmoback** [comment]
what i want is to set the empty image with border to only for those star which is empty, but not partially filled.

**Comment by evgenyneu** [comment]
@Karthikmoback hmmm I'm not sure this is possible with Cosmos. It simply draws "filled" image on top of "empty" one. And when start is partially filled it just draws a part of "filled" but it still draws entire "empty" image.

**Comment by Karthikmoback** [comment]
@evgenyneu thanks for the support. I made use of empty image border with same color of fill color, to make to look good.
