### ISSUE TITLE
Can you please build the framework for the Simulator

### ISSUE THREAD

**Issue by zahoorahmadgorsi** [evgenyneu/Cosmos#183]
Please consider submitting the following information (if relevant):

* Library setup method:,Carthage, CocoaPods
* Version of the library. 23.0
* Xcode version. Example: 812.4
* OS version. Example: iOS 14

When running in debug mode from Xcode with debug session active, the app launches in the simulator and I am able to debug.
But when I am trying to launch the app in the simulator without debug session (by double clicking on the icon), it crashes with the log message below.

Everything is fine on the real device.

Can you please build the framework for the Simulator?

**Comment by evgenyneu** [comment]
Hi @zahoorahmadgorsi thanks for reporting the problem. Could you attache the error message please?

**Comment by zahoorahmadgorsi** [comment]
Aww I am sorry, it wasn't the framework issue. 

I fixed it by following [these](https://www.raywenderlich.com/7649117-carthage-tutorial-getting-started) steps

Went to Build Phases. Click the + icon in the top-left of the editor and select New Run Script Phase. Add the following command to the block of code under Run Script:

/usr/local/bin/carthage copy-frameworks

Click the + icon under Input Files and add an entry for each framework:
$(SRCROOT)/Carthage/Build/iOS/Cosmos.framework

Issue is solved.

**Comment by evgenyneu** [comment]
Thank you so much for sharing the solution. Have a great day!
