### ISSUE TITLE
[Feature Request] Add custom image for half star

### ISSUE THREAD

**Issue by Ludotrico** [evgenyneu/Cosmos#184]
Please add the functionality to add your own images for **half** stars. Currently, you can only add custom images for empty/full.

**Comment by evgenyneu** [comment]
Hi @Ludotrico thanks for the request. What kind of functionality you want to achieve with the half star images?

**Comment by Ludotrico** [comment]
@evgenyneu At the moment there is half star precision but not if you supply custom images. This should be added:

CosmoView.settings.halfStarImage = ....

**Comment by evgenyneu** [comment]
Oh, half precision should work with current setup of full and empty image. What it does, it first draws the empty star, and then draws half of the full start on top of it. Have you tried it?

**Comment by Ludotrico** [comment]
Wow, i'm speechless, thanks!
