### ISSUE TITLE
Align rating to Right inside the cosmos uiview

### ISSUE THREAD

**Issue by umair151** [evgenyneu/Cosmos#55]
I want to align cosmos view to right without applying fixed size width constraint. For example I am having cosmos view of width 80 but it's actual content (i.e. 5 stars) are of width 60 which I want them to align right instead of left.

Please help.

**Comment by evgenyneu** [comment]
Hi @umair151. Thanks for the question. You are right about the fixed size width constraint, it is not necessary. Both width and height of the `CosmosView` are determined by the star sizes. You can change the star size in the Storyboard or from code:

```Swift
// Change the size of the stars
cosmosView.settings.starSize = 30
```

You can then use an auto layout constraint in your Storyboard and right-align alight the CosmosView to your other views. Let me know if it helps.

**Comment by evgenyneu** [comment]
@umair151 is this issue solved?

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
