### ISSUE TITLE
How to change left-to-right to right-to-left

### ISSUE THREAD

**Issue by smemamian** [evgenyneu/Cosmos#56]
hi

I sew new version supports right-to-left.
how can I change it to right to left ?

**Comment by evgenyneu** [comment]
Hi, good question. Cosmos view will automatically switch to right to left layout on phones with right to left languages. If your language is left to right, you can switch the language of your phone in iPhone settings to a right to left language. Or, you can change it in Xcode, schema settings > Application language > right to left pseudolanguage. Is it what you are asking?

**Comment by smemamian** [comment]
thanks for your quick answer. then isn't there any code for programmer to change left-to-right to right-to-left without changing setting?

**Comment by evgenyneu** [comment]
@smemamian is this issue solved?

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.

**Comment by Erumaru** [comment]
Force Right-to-Left doesn't work for me :(
