### ISSUE TITLE
How to move stars rating around within view controller?

### ISSUE THREAD

**Issue by winch-jm** [evgenyneu/Cosmos#58]
I created a view controller with class CosmosView and module Cosmos but the rating is displayed in the top right, opposite from the battery. I would like to be able to change the position of the rating.

**Comment by evgenyneu** [comment]
Hi, @winch-jm, thanks for the feedback. The Cosmos view was supposed to be subclassed from the `View` and not from the view controller. Is there a reason you are using View Controller?

**Comment by evgenyneu** [comment]
@winch-jm is this issue solved?

**Comment by winch-jm** [comment]
Yes thank you!

**Comment by evgenyneu** [comment]
Thanks, closing the issue. Feel free to reopen when needed.
