### ISSUE TITLE
On click of an already rated star how can I uncheck it

### ISSUE THREAD

**Issue by ArfaaShariff** [evgenyneu/Cosmos#59]
I have followed the readme and implemented the Cosmos view. 
I have set the fill mode to  half. However only from the second star I am able to rate half a star. The first star fills up completely.
Also on click of a star that is already filled I want to uncheck it i.e I want the rating to be 0 if the rating was 1 . How can I solve this?

**Comment by evgenyneu** [comment]
Hi, good questions.

> I have set the fill mode to half. However only from the second star I am able to rate half a star. The first star fills up completely.

Did you try setting `cosmosView.settings. minTouchRating = 0`? By default, the minimum rating is `1`.

> Also on click of a star that is already filled I want to uncheck it i.e I want the rating to be 0 if the rating was 1 . How can I solve this?

Does touching on on the left (for left hand language) from the star remove the rating?

**Comment by evgenyneu** [comment]
@ArfaaShariff is this issue resolved?

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
