### ISSUE TITLE
I am receiving a warning that M_PI is deprecated in Xcode 8.3.3

### ISSUE THREAD

**Issue by carlosdelamora** [evgenyneu/Cosmos#62]
/Users/carlosdelamora/Desktop/my apps/MonEx/Pods/Cosmos/Cosmos/CosmosLayers.swift:93:56: 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting.

In order to change it to Double.pi as the message suggest I need to unlock cosmos code, I do not want to do this. Is there another way around it, like an update or something?

**Comment by evgenyneu** [comment]
Thanks for reporting. There is a [separate version](https://github.com/evgenyneu/Cosmos#swift-40--xcode-90-beta-version) for Swift 4.0 / Xcode 9.0 beta. Let me know if it helps. :)

**Comment by evgenyneu** [comment]
Oh, sorry, I did not notice that you were using Xcode 8. The `pi` warning has been fixed, please update to the [most recent](https://github.com/evgenyneu/Cosmos#setup) stable version.

**Comment by carlosdelamora** [comment]
Thank you very much, It took me a while to update my pods because I was having issues with other dependencies. But now everything is working fine no warnings for me.

**Comment by evgenyneu** [comment]
No worries, all the best.
