### ISSUE TITLE
How to trigger an action after user selecting certain number of stars

### ISSUE THREAD

**Issue by fkeufss** [evgenyneu/Cosmos#63]
How to trigger an action after user selecting certain number of stars, e.g. if user selected all five stars that are shown, the app wants to show an alert. 

The author provided two functions:

// Called when user finishes changing the rating by lifting the finger from the view.
// This may be a good place to save the rating in the database or send to the server.
cosmosView.didFinishTouchingCosmos = { rating in }

// A closure that is called when user changes the rating by touching the view.
// This can be used to update UI as the rating is being changed by moving a finger.
cosmosView.didTouchCosmos = { rating in }

which seem to be for the purpose. 

Can you please tell me where I can use the above pieces of code? You do not seem to provide any deletage like UITableView. 

I am a beginner iOS programmer so I really hope you can help.

**Comment by evgenyneu** [comment]
Thanks for your question. :) Did you create cosmos view in the Storyboard? If so, do you know how to create an outlet for the cosmos view in your view controller code?

**Comment by fkeufss** [comment]
Thank you evgenyeu. I already found the solution. I created cosmos view in the Storyboard and created an outlet. I defined the function that it should trigger in the block cosmosView.didFinishTouchingCosmos = { rating in }. I think this is called "closure" and I just learned how to use it today. Very nice feature.

**Comment by evgenyneu** [comment]
Excellent! Good luck. :)

**Comment by evgenyneu** [comment]
Closing the issue, feel free to reopen if needed.

**Comment by rahulshine** [comment]
In my appliaction if user is selectiing bellow 4 we show orange and more than 4 show pink colour.
How to we Identify how many stars user is selected.

**Comment by evgenyneu** [comment]
@rahulshine, the `rating` argument passed to the `didTouchCosmos` and `didFinishTouchingCosmos` contains the selected rating, which is the selected number of stars.

For example:

```
cosmosView.didTouchCosmos = { rating in
   // Change the UI based on the `rating`
}
```

Let me know if it helps. :)
