### ISSUE TITLE
None of your spec sources contain a spec satisfying the dependency

### ISSUE THREAD

**Issue by udayasri** [evgenyneu/Cosmos#65]
Hi , 
pod 'Cosmos', '~> 11.0' seems not working .I'm getting this error 

**None of your spec sources contain a spec satisfying the dependency: `Cosmos (~> 11.0)`.**
Any idea about the error ? it it a branch issue ?

**Comment by evgenyneu** [comment]
Hi, thanks for reporting. I did some googling I found [this](https://github.com/CocoaPods/CocoaPods/issues/5545) discussion. People recommend running `pod repo update`  and if that does not help, try deleting Podfile.lock. Let me know if it helps. :)

**Comment by udayasri** [comment]
thanks a lot .. `pod repo update` worked fine ..

**Comment by evgenyneu** [comment]
No worries, I am glad it worked :)

**Comment by Farouk16** [comment]
it doesn't work for me :/ when i run `pod install` it still tells me that there's an error

**Comment by evgenyneu** [comment]
@Farouk16, see my answer in #70.
