### ISSUE TITLE
cosmosView.settings.filledImage = UIImage(named: "GoldStarFilled")

### ISSUE THREAD

**Issue by eastswift** [evgenyneu/Cosmos#66]
settings .FilledImage is missing. I can not replace the image.

**Comment by evgenyneu** [comment]
Hi, thanks for reporting. This feature was recently added to the library. Are you using the recent version?

**Comment by eastswift** [comment]
Okay. Thank you. I usung old version

**Comment by evgenyneu** [comment]
No worries.
