### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by tevghenii** [evgenyneu/Cosmos#67]
Hello,

Thanks for the library. I used it in my app it was very easy to setup and use it.
Do you consider to add support for animations? That would be nice to fill stars animatable.

Thanks!

**Comment by evgenyneu** [comment]
Hi, thanks for kind words and the idea. I've never thought of that. Could you describe how the animation would work from the user perspective? :)

**Comment by evgenyneu** [comment]
Closing the issue, feel free to reopen when needed.
