### ISSUE TITLE
Almost no response when touching a CosmosView created programmatically

### ISSUE THREAD

**Issue by top2tech** [evgenyneu/Cosmos#68]
Created a CosmosView programmatically. The stars can show correctly, but 90% of the time there is no response when touching it. And 10% of the time when I get lucky, it responds with stars filled. There is no problem if using it in Storyboard.
Note:
I did not set cosmosView.Settings.updateOnTouch or cosmosView.isUserInteractionEnabled, and even if I explicitly set them to true, same issue.

Below is the code:

```swift
 var cosmosView = CosmosView()       
 cosmosView.rating = 4
 cosmosView.text = "(123)"
 self.view.addSubview(cosmosView)
```
* Library setup method: CocoaPods 
* Version of the library: 11.0.3.
* Xcode version: 8.3.3.
* OS version : iOS 10.3.3

**Comment by evgenyneu** [comment]
Hi, thanks for reporting. This is very weird. I created a demo app and it worked for me. Please find attached. Maybe there is something specific to your app that breaks it?

[CosmosDemo.zip](https://github.com/evgenyneu/Cosmos/files/1186062/CosmosDemo.zip)

Let me know what you find out. :)

**Comment by top2tech** [comment]
Thanks a lot. With your attached sample, it works fine. I will check what I've missed

**Comment by top2tech** [comment]
Got a repro by modifying your example as below:
1. Remove Main.storyboard
2. Use auto  layout programmatically
Looks like it's related to using auto layout programmatically.

Please see attached zip code file.
[CosmosDemo-AutoLayout-TouchIssue.zip](https://github.com/evgenyneu/Cosmos/files/1195956/CosmosDemo-AutoLayout-TouchIssue.zip)

**Comment by evgenyneu** [comment]
Without a storyboard I think one needs to set the background color for the window in the app delegate:

```
self.window?.backgroundColor = UIColor.white
```

I have no idea why, but that's what people are doing. :) Let me know if it helps.

**Comment by top2tech** [comment]
Though we don't know the root cause, but setting window or a ViewController's background is an easy workaround. Thanks.
