### ISSUE TITLE
i can't add custom images

### ISSUE THREAD

**Issue by HaiIamRay** [evgenyneu/Cosmos#69]
Please consider submitting the following information (if relevant):

* Library setup method: file, Carthage, CocoaPods or Swift Package Manager.
* Version of the library. Example: 8.0.
* Xcode version. Example: 8.3.3.
* OS version. Example: iOS 10.3.2.

**Comment by evgenyneu** [comment]
Hi, thanks for reporting. Could you describe your problem please? What is preventing you from showing star images?

**Comment by evgenyneu** [comment]
Do you still have the problem, @HaiIamRay?

**Comment by evgenyneu** [comment]
Closing the issue, feel free to reopen if needed.
