### ISSUE TITLE
pod install gives me an arror

### ISSUE THREAD

**Issue by Farouk16** [evgenyneu/Cosmos#70]
So I'm working on a project using the latest version of firebase, when I write down the pods for my project : `  # Pods for knowmorocco
pod 'Firebase/Core'
pod 'Firebase/Core/Auth'
pod 'Firebase/Core/Database'
pod 'Firebase/Core/Storage'`

and go to the terminal and run `pod install` it gives me this error - `Firebase/Core/Storage` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Firebase/Core/Storage`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

I've tried the `pod install --repo-update` but still does not work :/

**Comment by evgenyneu** [comment]
Hi, I have no idea, sorry. I would suggest to ask on [stackoverflow](https://stackoverflow.com/).
