### ISSUE TITLE
Is there possible to star alignment from right to left?

### ISSUE THREAD

**Issue by Saravana181187** [evgenyneu/Cosmos#71]
I want to align the star from right to left it is possible or not? 
And my another problem is how to make the stars as center(It mean middle of the cosmos view now it is left side) of the view?

**Comment by evgenyneu** [comment]
Hi, thanks for the questions.

"I want to align the star from right to left it is possible or not?"

If you want to align the cosmos view to the right edge of the view, you can do it with Auto Layout. Cosmos view behaves like any other view, so just add a constraint to the right of the view.

"And my another problem is how to make the stars as center(It mean middle of the cosmos view now it is left side) of the view?"

Sorry, I did not understand what you mean. Can you draw a picture maybe? :)

**Comment by otymartin** [comment]
@evgenyneu right now the stars either align to the left of the view or the right. By default I would assume the width of the cosmosView would be equal to the width of the number of stars + it's insets instead its width is equal to the width of my parentView meaning when i try to center it in my parentView, it never centers. it just aligns to the left.

**Comment by evgenyneu** [comment]
@Saravana181187, do you still have the issue?

@otymartin, I'm glad you found the solution! 👍

**Comment by Saravana181187** [comment]
@evgenyneu , Yes still I have issue.

**Comment by evgenyneu** [comment]
@Saravana181187, could you tell me more about your issue so I can help? See my questions above.

**Comment by Saravana181187** [comment]
I want to set or align stars from right to left, If I swipe right to left means stars want to increase, the first star starts from right side.

**Comment by Saravana181187** [comment]
Thank you very much it helps me .

**Comment by evgenyneu** [comment]
I'm glad it helped.
