### ISSUE TITLE
Is there possible way to first star turn to empty while using "fillMode = .half"

### ISSUE THREAD

**Issue by techphantcg** [evgenyneu/Cosmos#72]
I am using the 
cosmosview.settings.fillMode = .half

when i scroll over stars the first stat always be filled, in my case needs to be empty or rating value needs to be zero

Thanks!

**Comment by evgenyneu** [comment]
Hi @techphantcg , thanks for the question. There is a `minTouchRating` setting that controls the minimum rating the user can set. But default it is `1`, but you can change it to `0` to allow setting the zero rating:

```
cosmosview.settings.minTouchRating = 0
```

You can view other [configuration settings](https://github.com/evgenyneu/Cosmos/wiki/Cosmos-configuration) in the Wiki. Let me know if it helps. :)

**Comment by techphantcg** [comment]
Hi @evgenyneu 

Thanks for your reply

`cosmosview.settings.minTouchRating = 0`

worked for me

**Comment by evgenyneu** [comment]
Great, I'm glad it worked.
