### ISSUE TITLE
Is RTL Languages Supported?

### ISSUE THREAD

**Issue by mn288** [evgenyneu/Cosmos#74]

**Comment by evgenyneu** [comment]
Yes :)

**Comment by mn288** [comment]
If I switch to an RTL Language, the stars don't switch to RTL
I added the Cosmos view via Interface Builder and added it in a stack view; in a custom UICollectionViewCell

_**Using latest Xcode 8.3.3 and latest Update of the Library_

**Comment by evgenyneu** [comment]
Hi, thanks for reporting. I created a demo app with collection view and placed a cosmos view inside a stack view. However, I could not reproduce your problem. The cosmos view flipped to right-to-left mode after I switched my phone to Hebrew (Settings > General > Language & Region).

Please see the attached demo app below.
[CosmosRTLDemo.zip](https://github.com/evgenyneu/Cosmos/files/1259563/CosmosRTLDemo.zip)

You probably know this, but just for the record:

- One needs to add the localization for the right-to-left language in the project settings, in order for it to work.
- One can quickly test right-to-left layout by choosing Edit Scheme > Application Language > Righ-to-left pseudolanguage.

Maybe there is something specific to your app that I did not try?

<img src="https://user-images.githubusercontent.com/880411/29810854-cd31fe48-8ce4-11e7-9525-6bb44763470e.png" width="320" alt="Tesing right-to-left layout in Cosmos iOS star rating control">

**Comment by evgenyneu** [comment]
@mn288 please let me know if you still have the problem :)

**Comment by mn288** [comment]
I am sorry for the late response, seems something was wrong with my email notifications. I still face the same problem. 

I tried your sample project, it works beautifully with Hebrew, but with Arabic, it isn't working as it should

**Comment by evgenyneu** [comment]
It's ok @mn288. The sample project will not show right-to-left layout unless one adds a localization for Arabic language in Project > Into. Please see the screenshot attached. Let me know if it fixes the problem.

<img width="600" alt="xcode_lolizations_rtl_cosmos" src="https://user-images.githubusercontent.com/880411/31050290-94ce3c76-a691-11e7-853f-d3ba5c4f8316.png">

**Comment by mn288** [comment]
Although the last step you mentioned was already implemented, I solved the problem by:
1. Removed all the localizations
2. Removed Derived Data folder
3. Cleaned the Project
4. Added localization files from scratch.

Thanks a lot

**Comment by evgenyneu** [comment]
I'm glad it worked, thanks for sharing your solution. 👍

**Comment by evgenyneu** [comment]
@wajihkm creating a new issue #132.
