### ISSUE TITLE
swift 4 support

### ISSUE THREAD

**Issue by mickychen0524** [evgenyneu/Cosmos#75]
I am running on xCode 9 and getting compile error

**Comment by evgenyneu** [comment]
Hi, thanks for reporting. Did you use the [Xcode 9 installation instructions](https://github.com/evgenyneu/Cosmos#swift-40--xcode-90-beta-version)?

**Comment by mickychen0524** [comment]
yes, it works!

**Comment by evgenyneu** [comment]
Nice! Xcode 9 version will be released soon.
