### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by yamakhalah** [evgenyneu/Cosmos#76]
Hello, using last Xcode version and iOS 11. That error message:

/Users/dylandivito/hairdresserios/Hairdresser/Pods/Cosmos/Cosmos/CosmosLayerHelper.swift:17:43: Incorrect argument label in call (have 'withAttributes:', expected 'attributes:')

That call seems completely deprecated

https://puu.sh/xKTww/07b4f54e6e.png

Could you fix this please ?

**Comment by evgenyneu** [comment]
Hi @yamakhalah, thanks for reporting. You are seeing this with the latest version of Cosmos library?

**Comment by yamakhalah** [comment]
Yep version 12.0.1

**Comment by evgenyneu** [comment]
Cool, what's the Swift Language Version in the build settings of your target?

**Comment by yamakhalah** [comment]
Swift 4.0, tried with swift 3.2 but didn't fix it

**Comment by yamakhalah** [comment]
Oh ok my bad the pod was in swift 3.2 so, fixed.

Thank you :)

**Comment by evgenyneu** [comment]
No worries, I'm glad it's fixed :)

**Comment by nick-potts** [comment]
I'm really struggling with this. I'm getting the exact same build error, but changing swift version doesn't seem to work.

**Comment by yamakhalah** [comment]
Don't forget to do it in your project AND in the framework target

https://puu.sh/xL0Io/c0c11072f5.png

**Comment by jeremypiednoel** [comment]
Hi @yamakhalah do you know when you will publish the new version with this fix ?
The cocoapods version is  12.0.1 with the error : https://cocoapods.org/pods/Cosmos
Thanks.

**Comment by evgenyneu** [comment]
@jeremypiednoel, sorry what fix do you mean exactly? What is your error?

**Comment by evgenyneu** [comment]
I can't reproduce this problem. If you use version 12 of Cosmos, make sure to set Swift Language Version to `4.0` in the Build Settings. Please note that this needs to be done in the Cosmos target for the Pods project, as shown in the screenshot below.

<img width="968" alt="cosmos_swift_version" src="https://user-images.githubusercontent.com/880411/31150894-19a3c050-a8e1-11e7-991c-02b985c43f4b.png">

I'm also attaching a demo app:

[UseCosmos.zip](https://github.com/evgenyneu/Cosmos/files/1353996/UseCosmos.zip)

**Comment by jeremypiednoel** [comment]
Thanks @evgenyneu , so is that a problem with cocoapods and swift 4 compatibility ?

**Comment by evgenyneu** [comment]
@jeremypiednoel, good question. I don't know what is causing your issue, so I can't say. But if I create a new project from scratch in Xcode 9, add Cosmos to Podfile and run `pod install`, the Swift Language Version is set correctly `4.0` from the start. Maybe this issue appears when you migrate an existing project from version `3.2` Swift project to `4.0`.

**Comment by jeremypiednoel** [comment]
@evgenyneu Thanks i'll change it manually then.
