### ISSUE TITLE
CFBungleIdentifier missing

### ISSUE THREAD

**Issue by yamakhalah** [evgenyneu/Cosmos#77]
Hey, me again.

The app installation fail. Here is the error in CoreSimulator.log

ep 28 17:06:36 MacBook-Pro-de-Dylan com.apple.dt.Xcode[57428] <Error>: installApplication:withOptions:error:: Error Domain=IXUserPresentableErrorDomain Code=2 "This app was unable to be installed." UserInfo={NSLocalizedDescription=This app was unable to be installed., NSUnderlyingError=0x7fee976c6fb0 {Error Domain=MIInstallerErrorDomain Code=12 "Bundle at path /Users/dylandivito/Library/Developer/CoreSimulator/Devices/B4D283A1-4179-4959-912E-968C797B58BE/data/Library/Caches/com.apple.mobile.installd.staging/temp.12MHLl/extracted/Hairdresser.app/Frameworks/Cosmos.framework did not have a CFBundleIdentifier in its Info.plist" UserInfo={LegacyErrorString=MissingBundleIdentifier, FunctionName=-[MIBundle _validateWithError:], SourceFileLine=45, NSLocalizedDescription=Bundle at path /Users/dylandivito/Library/Developer/CoreSimulator/Devices/B4D283A1-4179-4959-912E-968C797B58BE/data/Library/Caches/com.apple.mobile.installd.staging/temp.12MHLl/extracted/Hairdresser.app/Frameworks/Cosmos.framework did not have a CFBundleIdentifier in its Info.plist}}}

So the CFBundleIdentifier is missing and i don't understand why.

Using Xcode 9 / iOS 11 / Cosmos last version

https://puu.sh/xL0Se/3d881f7cca.png

Thank you :)

**Comment by evgenyneu** [comment]
Hi again :) I've no idea, have not seen this error before. Try Googling the error message or ask on stackoverflow.

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
