### ISSUE TITLE
Swift 3.2 could not build

### ISSUE THREAD

**Issue by Jinkeycode** [evgenyneu/Cosmos#78]
Swift 3.2 could not build

* Library setup method: CocoaPods
* Version of the library. Example: 12.0.1.
* Xcode version. Example: 9.1-beta.
* OS version. Example: iOS 10.3.3.
* Swift version. Example: 3.2.

**Comment by evgenyneu** [comment]
Thanks for reporting. Did Xcode show any error messages? Those would be useful for me to investigate your problem.

**Comment by blerchy** [comment]
I am also having an issue with Swift 3.2

It's having this error:
`Incorrect argument label in call (have 'withAttributes:', expected 'attributes:')`

On line 7  in `CosmosLayerHelper.swift`

**Comment by evgenyneu** [comment]
Hi @blerchy, it looks like your Swift Language Version in your Build Settings is set to 3 but you are using the recent version of Cosmos which is in Swift 4. If that's true, I would suggest changing the swift version to 4 or using the [previous version](https://github.com/evgenyneu/Cosmos/wiki/Legacy-Swift-versions) of Cosmos.

**Comment by blerchy** [comment]
@evgenyneu Oops, that's a rookie mistake! Thanks so much for your help.

**Comment by evgenyneu** [comment]
It's alright, I'm glad it's sorted. :)

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
