### ISSUE TITLE
How to center stars in view?

### ISSUE THREAD

**Issue by foolbear** [evgenyneu/Cosmos#80]
Please consider submitting the following information (if relevant):

* Library setup method: file, Carthage, CocoaPods or Swift Package Manager.
* Version of the library. Example: 8.0.
* Xcode version. Example: 8.3.3.
* OS version. Example: iOS 10.3.2.

**Comment by evgenyneu** [comment]
Hi, stats should be always centered, as soon as there are no constraints on width/height. More on this [here](https://github.com/evgenyneu/Cosmos#positioning-the-cosmos-view).
