### ISSUE TITLE
getting this issue suddenly in my project 

### ISSUE THREAD

**Issue by harshit-mapmyindia** [evgenyneu/Cosmos#81]
Please consider submitting the following information (if relevant):

* Library setup method: file, Carthage, CocoaPods or Swift Package Manager.
* Version of the library. Example: 8.0.
* Xcode version. Example: 8.3.3.
* OS version. Example: iOS 10.3.2.

**Comment by harshit-mapmyindia** [comment]
getting this issue suddenly in my project 

<img width="773" alt="screen shot 2017-10-10 at 5 46 46 pm" src="https://user-images.githubusercontent.com/32668977/31386049-18f2ff70-ade3-11e7-901e-b82291d0a573.png">

**Comment by pvroosendaal** [comment]
me too!

**Comment by evgenyneu** [comment]
Hi @harshit-mapmyindia, it looks like your Swift Language Version in your Build Settings is set to 3 but you are using the recent version of Cosmos which is in Swift 4. If that's true, I would suggest changing the swift version to 4 (including the CocoaPods target) or using the previous version of Cosmos, as @pvroosendaal suggested.

**Comment by clausholm** [comment]
Same problem here. But Xcode won't let me update to Swift 4 when the projects can't build. So I tried installing an earlier cocoapod version like suggested:

**# Pods for rating “stars”
pod 'Cosmos', '~> 11.0'**

Looks like it installed succesful:
**82:Concert Rating App 2 clausholm$ sudo gem install cocoapods
Successfully installed cocoapods-1.3.1
Parsing documentation for cocoapods-1.3.1
1 gem installed
82:Concert Rating App 2 clausholm$** 

Still get the same error mentioned above. Any ideas?

**Comment by pvroosendaal** [comment]
Use this fixed version in podfile: pod 'Cosmos', '11.0.3'

Did you do a 'pod update'? The terminal code only states you installed cocoapods...

**Comment by evgenyneu** [comment]
@clausholm, what's your "Swift Language Version" in your build settings (all targets including the cocoapods ones)?

**Comment by clausholm** [comment]
Updating instead of installing fixed it. Thank you guys! :-)

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
