### ISSUE TITLE
center view 

### ISSUE THREAD

**Issue by MahmoudAbunaji** [evgenyneu/Cosmos#83]
Please consider submitting the following information (if relevant):

* Library setup method: file, Carthage, CocoaPods or Swift Package Manager.
* Version of the library. Example: 8.0.
* Xcode version. Example: 8.3.3.
* OS version. Example: iOS 10.3.2.

**Comment by MahmoudAbunaji** [comment]
can i center the view that contain the stars to center ?

and what about auto. resize with screen ?

**Comment by evgenyneu** [comment]
Hi @MahmoudAbunaji, thanks for the question. You can center Cosmos by using the Auto Layout centering constraint. You can see how it is done in the demo app included in this project.

As for the resizing, I'm not sure what you are asking, sorry.

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
