### ISSUE TITLE
Update to Swift 4 reveals new issue: The following binaries use incompatible versions of Swift

### ISSUE THREAD

**Issue by KonradLo** [evgenyneu/Cosmos#84]
After I updated my App to Swift 4 I get this error message: 
**error: The following binaries use incompatible versions of Swift:**
/Users/Konrad/Library/Developer/Xcode/DerivedData/ExploreYourCity-btthjezgywzvnmduiurzwgwzrven/Build/Products/Debug-iphoneos/Cosmos/Cosmos.framework/Cosmos
/Users/Konrad/Library/Developer/Xcode/DerivedData/ExploreYourCity-btthjezgywzvnmduiurzwgwzrven/Build/Products/Debug-iphonesimulator/ExploreYourCity.app/ExploreYourCity
I can not find a solution to this misstake. Whats wrong?

* Library setup method: CocoaPods
* Version of the library. Example: 12.0.1.
* Xcode version. Example:9.0.1.
* OS version. Example: iOS 11.0.
*Swift Version: Swift 4.0.

**Comment by evgenyneu** [comment]
Hi, thanks for reporting. I have not seen such an error before, unfortunately. I would suggest searching the error text on [stackoverflow](https://stackoverflow.com/) or asking a question there. Sorry.

**Comment by evgenyneu** [comment]
Do you still have the issue?

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
