### ISSUE TITLE
Compilation Error in Class CosmosLayerHelper

### ISSUE THREAD

**Issue by dvautrelle** [evgenyneu/Cosmos#85]
Just add Cosmos in my project, and get a Compilation Error in Cosmos Class
`class func createTextLayer(_ text: String, font: UIFont, color: UIColor) -> CATextLayer {
    let size = NSString(string: text).size(withAttributes: [NSAttributedStringKey.font: font])
`

> **Incorrect argument label in call (have 'withAttributes:', expected 'attributes:')**

I precise that  my **Swift Language Version** in Build Settings is **4.0** (not 3.0)

* Library setup method:  CocoaPods (1.2.0)
* Version of the library. Example: 12.0.1.
* Xcode version. Example: 9.0.1
* OS version. Example: iOS 10.3.

**Comment by evgenyneu** [comment]
Thanks for reporting @dvautrelle. Is the Swift Language Version set to 4.0 in the cocoapod target as well?

**Comment by dvautrelle** [comment]
problem is solved by:
- declare the Swift version as 4.0 in:
 - Product Build Setting
 -  AND in ALL Target of your project
Then, force the clean of your project (menu product / Clean) and rebuild all your project

Thanks for your help

**Comment by ivanicspeter92** [comment]
I had the same problem, changing the Swift language version flag on the Cosmos target in the Pods project solves the issue.

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
