### ISSUE TITLE
Failed to render and update auto layout status (cw6-SP-FTO). The agent crashed

### ISSUE THREAD

**Issue by ludoergosum** [evgenyneu/Cosmos#87]
I have not created an issue in Github before, so please let me know if I´m doing anything wrong.

I have tried to follow the guide, but I don´t see stars in the storyboard and I I get the following error: Failed to render and update auto layout status (cw6-SP-FTO). The agent crashed.

![screen shot 2017-11-27 at 23 02 00](https://user-images.githubusercontent.com/16974609/33291732-228d504e-d3c7-11e7-8d8a-0e13fac0796f.png)
![screen shot 2017-11-27 at 23 02 29](https://user-images.githubusercontent.com/16974609/33291733-22b5e504-d3c7-11e7-8e19-d8008f940b1c.png)
![screen shot 2017-11-27 at 23 02 37](https://user-images.githubusercontent.com/16974609/33291734-22d93310-d3c7-11e7-8752-f3ae37ec018e.png)

Also tried to link the framework but no difference (this was  a shot in the dark)
![screen shot 2017-11-27 at 23 05 27](https://user-images.githubusercontent.com/16974609/33291840-7cd39572-d3c7-11e7-938c-10740357314c.png)

* Library setup method: file, CocoaPods
* Version of the library.: 11.03
* Xcode version. 8.3.3.
* OS version. iOS 10.3.2.

**Comment by ludoergosum** [comment]
I see now that it works in the simulator, but its of course hard to use it when I don´t see anything in the storyboard.

**Comment by evgenyneu** [comment]
Thanks for reporting.

"I see now that it works in the simulator, but its of course hard to use it when I don´t see anything in the storyboard."

That's very strange. A storyboard bug in the Xcode? I'm sure you tried "Editor/Refresh all views", clearing derived data and restarting Xcode?

```
rm -rfd ~/Library/Developer/Xcode/DerivedData/*
rm -rfd ~/Library/Caches/com.apple.dt.Xcode/*
```

**Comment by ludoergosum** [comment]
Hey,

Thank you for the quick reply.

I tried, refresh and clean, but I must admit I did not restart Xcode.
Did it now, and that seemed to have done the trick.

Hope you did not spend much time on this.

**Comment by evgenyneu** [comment]
Awesome!
