### ISSUE TITLE
Not supporting Swift 4

### ISSUE THREAD

**Issue by randhirkumarcse** [evgenyneu/Cosmos#88]
* Version of the library: 12.0.1
* Xcode version: 9.1
* OS version: 10.12.6

CosmosLayerHelper -> 
Line#17 -> let size = NSString(string: text).size(withAttributes: [NSAttributedStringKey.font: font])

it should be-> let size = NSString(string: text).size(attributes: [NSAttributedStringKey.font: font])

Please fix it ASAP.

**Comment by randhirkumarcse** [comment]
withAttributes -> attributes (to be specific)

**Comment by evgenyneu** [comment]
Hi, thanks for reporting. The current code is compatible with Swift 4. The `size` method has the `withAttributes` parameter in Swift 4. What might be causing your issue is that your `Swift Language Version` setting is not `4.0`, as shown in the image below. Please note that this needs to be done in the all your targets that use Swift 4, **including the CocoaPods targets**. Let me know if it works for you.

<img width="594" alt="xcode_swift_version" src="https://user-images.githubusercontent.com/880411/33417065-e2790dde-d5f3-11e7-93cf-16b8b03de01f.png">

**Comment by ducminh1012** [comment]
It's working for me.

**Comment by KellyBennett** [comment]
Excuse my ignorance because I've never put a pod together, but shouldn't this somehow be a part of the podspec, or in a settings file or something? I mean… it doesn't seem right that I have to set this manually every time I do a pod install. 

Thanks!

**Comment by randhirkumarcse** [comment]
Thanks @evgenyneu , As such there was no issue. sorry for the delayed response.

**Comment by evgenyneu** [comment]
@KellyBennett, as far as I know, CocoaPods does not set the version on pod install, unfortunately. [More info](https://github.com/CocoaPods/CocoaPods/issues/7134).

**Comment by KellyBennett** [comment]
@evgenyneu I see! Thanks for the quick response (and the very handy pod).
For anyone else having this issue, you can also set the swift version in the podfile.
```
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Be explicit about swift version
            if target.name == 'Cosmos' 
                config.build_settings['SWIFT_VERSION'] = '4.0'
                else
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end
```

**Comment by evgenyneu** [comment]
@miracleshivam, the current version 17 uses Swift 4.2 for Xcode 10. You might want to use the previous version 16 for Xcode 9. Please see the instructions [here](https://github.com/evgenyneu/Cosmos/wiki/Legacy-Swift-versions).

**Comment by miracleshivam** [comment]
@evgenyneu Thanks.

**Comment by agueroveraalvaro** [comment]
Update swift 4.2

`let size = NSString(string: text).size(withAttributes: [NSAttributedString.Key.font: font])`
