### ISSUE TITLE
Changing size of individual star?

### ISSUE THREAD

**Issue by Raymond26** [evgenyneu/Cosmos#9]
Hi, great work with the library!

Is there a way to change the size of one star and keep the others unchanged?  I want the size of one star to increasingly get bigger the longer a user holds it.

**Comment by evgenyneu** [comment]
Hi, there is no way of making stars of different sizes right now. Unlike real cosmos all the stars here are the same.

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen when needed.
