### ISSUE TITLE
cosmosView.fillMode=.precise not working :(

### ISSUE THREAD

**Issue by julioas09** [evgenyneu/Cosmos#90]
Environment:
* I setup the environment by adding the .swift file to my project.
* Xcode version: 9.1
* OS version: iOS 11.1

I'm setting up a display for star rating without user interaction (I set the rating programmatically).
The issue is that using the following code, it doesn't work as intended. It displays the same as using .half.

```
cosmosView.isUserInteractionEnabled = false
cosmosView.settings.fillMode = .precise
cosmosView.rating = 3.8
```

If I activate user interaction, I can set it correctly as "precise" (not full or half starts, but also in between) by interacting with it, however setting it programmatically still behaves as if it was .half :S.

Any insights about this?

Thanks!!

**Comment by evgenyneu** [comment]
Thanks for reporting, @julioas09. Unfortunately I could not reproduce your problem. I've created an new app and with your code it does set the correct rating. Am I missing something else? Please find the project attached.

[DemoCosmos.zip](https://github.com/evgenyneu/Cosmos/files/1586184/DemoCosmos.zip)

**Comment by julioas09** [comment]
Hmm thanks for the quick response. It does work in your test app. 
Which I also noticed is that I can't see the stars in my storyboard preview, only when I run the app.
I'll try to find out what's wrong...

**Comment by julioas09** [comment]
Hi! I was playing around and I noticed that I couldn't see the correct behaviour because of the stars scale. It does work properly.
Sorry to bother you! Thanks!

**Comment by evgenyneu** [comment]
No worries, happy holidays!
