### ISSUE TITLE
Use of undeclared type 'CosmosView'

### ISSUE THREAD

**Issue by bbookman** [evgenyneu/Cosmos#95]
xcode v9.2, swift 4
My repo https://github.com/bbookman/MVP/tree/broken

The following code gives me a compile error

` @IBOutlet weak var cosmosViewFull: CosmosView!`

Error: Use of undeclared type 'CosmosView'

The CosmosView is in a custom view controller "Location Detail View Controller" with custom class "LocationDetailViewController".  This view controller contains two views.  "Location Detail View" and inside that the "Cosmos Rating" CosmosView.  Yes, CosmosView is set as custom class for "Cosmos Rating".  And "Location Detail View" is just a UIView.

**Comment by bbookman** [comment]
never mind :( . RTFM

**Comment by jlmarechal** [comment]
hello, I'm having the same issue. How did you fix it?

**Comment by bbookman** [comment]
Wow I wish I could remember!  Since I said "RTFM" ..  I must have missed something in the readme instructions.  My only suggestion is to very carefully read the instructions again.  Sorry I can't be more help, but this was a while ago.  Cosmos is working fine for me and it has been a while since I touched it.

**Comment by jlmarechal** [comment]
Thanks man for your the quick response. It looks like the target membership was the culprit. I unchecked the tests and UItests target and everything works

**Comment by bbookman** [comment]
I'm happy you fixed it and I'm bummed I could not remember my fix :(.  Hopefully others will find this thread useful.  

Would you be willing to do me a big favor?  I'm working on a Youtube channel for iOS development and could use some harsh critique ;) .  I've got two playlists that very much need other's eyes. 

One is Tutorials: https://youtu.be/gxMj7TzOqfU
The other is "The Bumbling Dev": https://youtu.be/Zsxu5yFl5ok

Thank you in advance.  Best of luck on your project

**Comment by jlmarechal** [comment]
Sure I’ll be glad to look at your playlist. I’ll get back to you

**Comment by dev-Anup** [comment]
"import Cosmos" did the trick for me.
