### ISSUE TITLE
Not possible to correctly reuse Cosmos view

### ISSUE THREAD

**Issue by xrayman** [evgenyneu/Cosmos#97]
Cosmos (12.0.1)

Hi

There's an issue when you use cosmos view inside reusable view, like tableview cell, with updateOnTouch turned on. When cell is being reused you won't be able to set the same rating which was in the cell before reuse. Because of "previousRatingForDidTouchCallback" private variable which stores previously selected rating.

I've slightly modified demo project to illustrate the issue:
![untitled-2](https://user-images.githubusercontent.com/2477404/36291519-1867cc1a-12d4-11e8-9f17-9ccc19b50c9d.gif)

Resetting previousRatingForDidTouchCallback value in didSet for rating solves this issue.

**Comment by evgenyneu** [comment]
Hi @xrayman, thanks for reporting the issue. Can you attach the source code for the demo that you modified please?

**Comment by xrayman** [comment]
@evgenyneu https://github.com/xrayman/Cosmos
I've created a fork and pushed modified demo there

**Comment by evgenyneu** [comment]
That's a very good point, @xrayman. I've added a new function `prepareToReuse` to the CosmoView. Here is an example of usage. This update is released as version 15. Thanks for your help!

```Swift
public class PerformanceTableViewCell: UITableViewCell {
  @IBOutlet var cosmosView: CosmosView!
 
  override public func prepareForReuse() {
    // Ensures the reused cosmos view is as good as new
    cosmosView.prepareForReuse()
  }
}
```

**Comment by xrayman** [comment]
Great! Thank you!
