### ISSUE TITLE
Failed to download 'Cosmos'.

### ISSUE THREAD

**Issue by akjesto** [evgenyneu/Cosmos#99]
I got the following error when I tried 'pod install' command in my terminal

**Pre-downloading: `Cosmos` from `https://github.com/evgenyneu/Cosmos.git`, branch `swift-4.0`**

**[!] Error installing Cosmos**
**[!] Failed to download 'Cosmos'.**

My podfile look like this
**pod 'Cosmos', :git => 'https://github.com/evgenyneu/Cosmos.git', :branch => 'swift-4.0'**

My pod version is  1.4

**Comment by evgenyneu** [comment]
Hi, I think it fails because there is no branch swift-4.0 anymore. You can
try using the latest version instead, as shown in the setup section of the
readme.

**Comment by evgenyneu** [comment]
Closing the issue. Feel free to reopen if needed.
